Упражнение 1. Записать следующие команды (каждую в своей ячейке).
1) 2*3
2) k=3+4
print(k)
3) (k+1)*(k-1)
4) (x+1)*(x-1)

In [2]:
2*3

6

In [3]:
k=3+4
print(k)

7


In [4]:
(k+1)*(k-1)

48

In [5]:
h=(k+2)*3+\
3+(k+7)
print(h)

44


Упражнение 3.
1) Убрать из рабочего пространства все переменные.
2) Ввести переменные x, y, z, t, задав им значения соответственно 1, 2, 3, 4.
3) Вывести в командное окно информацию обо всех переменных.
4) Удалить из рабочего пространства переменную x.
5) Вывести в командное окно информацию об оставшихся переменных.
6) Вывести в командное окно информацию об оставшихся переменных.

In [6]:
%reset

x = 1
y = 2
z = 3
t = 4

print(x, y, z, t)

del(x)

print("after delete:", y, z, t)

1 2 3 4
after delete: 2 3 4


Пример описания матрицы:
$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$

In [7]:
import numpy as np

A = np.array( [ [1, 2, 3, 4], [0, 1, 3, 2] ] )

print(A)

print("column: ", A[:,0])
print("line: ", A[0,:])

[[1 2 3 4]
 [0 1 3 2]]
column:  [1 0]
line:  [1 2 3 4]


In [8]:
v = np.arange(1,8,2)
print (v)

[1 3 5 7]


In [9]:
A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Упражнение 4.
1) Задать какую-нибудь матрицу R размерностью . Отобразить её
сначала в текстовой ячейке в режиме Markdown. Затем ввести её в кодовой
ячейке с помощью модуля numpy.

2) Заменить значения элемента R(2,3) на противоположный (R(2,3)= -R(2,3)), вывести обновленную матрицу R в командное окно. Уменьшить на 4
элемент, стоящий в первой строке и третьем столбце, вывести обновленную
матрицу R в командное окно. Удвоить все элементы второго столбца. Утроить
все элементы первой строки.

3) Задать векторы-строки размерности и , задать 3 вектора-столбца
разной размерности.

1) $\begin{bmatrix} 6 & 6 & 6 \\ 7 & 7 & 7 \\ 3 & 2 & 2 \end{bmatrix}$

In [10]:
R = np.array( [ [6, 6, 6], [7, 7, 7], [3, 2, 2] ] )

print("before: \n", R, "\n")

R[1, 2] = -R[1, 2]

print("after negative: \n", R, "\n")

R[0, 2] -= 4

print("after minus: \n", R, "\n")

R[:,1] *= 2
R[0,:] *= 3

print("after mult: \n", R)

before: 
 [[6 6 6]
 [7 7 7]
 [3 2 2]] 

after negative: 
 [[ 6  6  6]
 [ 7  7 -7]
 [ 3  2  2]] 

after minus: 
 [[ 6  6  2]
 [ 7  7 -7]
 [ 3  2  2]] 

after mult: 
 [[18 36  6]
 [ 7 14 -7]
 [ 3  4  2]]


In [11]:
V_S1 = np.array([1, 2, 3, 4, 5])
V_S2 = np.array([1, 2, 3, 4, 5, 6, 7])

print("Vector-strings: ")
print(V_S1)
print(V_S2)

V_C1 = np.array([[1], [2], [3]])
V_C2 = np.array([[1], [2], [3], [4]])
V_C3 = np.array([[1], [2], [3], [4], [5]])

print("Vector-columns :")
print(V_C1)
print(V_C2)
print(V_C3)

Vector-strings: 
[1 2 3 4 5]
[1 2 3 4 5 6 7]
Vector-columns :
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]
 [5]]
